var express = require('express')
var todoController = require('./controller/todoController.js')
var app = express()
app.set('view engine', 'ejs')
app.use(express.static('./public'))
todoController(app)
app.listen(8088)